### ISSUE TITLE
FAILED Compilation

### ISSUE THREAD

**Issue by mekhea** [sgieseking/anyrpc#30]
hi,
I try to build your lib again. But now the compilation failed. Maybe after your last merge (24/01/2017). why you did not use a Branch or Tag to keep the old version code and the new with the modifications.

   std::condition_variable condVarDelayedRemove_;
          ^
/data/IPC_TESTS/anyrpc/src/method.cpp: In member function ‘bool anyrpc::MethodManager::RemoveMethod(const string&, bool)’:
/data/IPC_TESTS/anyrpc/src/method.cpp:114:17: error: ‘condVarDelayedRemove_’ was not declared in this scope
                 condVarDelayedRemove_.wait(lock);
                 ^
/data/IPC_TESTS/anyrpc/src/method.cpp: In member function ‘void anyrpc::MethodManager::ExecuteMethod_FollowUpOperations(anyrpc::Method*)’:
/data/IPC_TESTS/anyrpc/src/method.cpp:167:9: error: ‘condVarDelayedRemove_’ was not declared in this scope
         condVarDelayedRemove_.notify_all(); // notify waiting calls of remove method (if any)
         ^
make[2]: *** [src/CMakeFiles/anyrpc.dir/method.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/anyrpc.dir/all] Error 2
make: *** [all] Error 2

**Comment by sgieseking** [comment]
The git repository has the full history of the code modifications.  You can pull the older version if that is what you want.  Tags are only necessary to mark important changes such as a formal revision change and really just give an easy way to find a particular version.  I have not normally used these with minor updates.

You might verify that you have a clean version of the latest code by either performing a new git clone or a reset on the head version.  Assuming that you are doing the build in a separate directory, delete all contents of the directory and start over from cmake.

It would help to provide more information on the OS that you are using and any other aspects of the compilation environment that might be important.  I primarily compile on Ubuntu 14.04 but it frequently gets checked on Windows VS2013 and VS2015.

The error seems to be from the compiler not recognizing std::condition_variable.  This is formally defined in the library <condition_variable> which looks like it is not explicitly included.  Many times these get implicitly included by other libraries and therefore are not noticed.  Try adding this include to either api.h or method.h.
#include <condition_variable>

**Comment by mekhea** [comment]
Hi Steve,


I am using ubuntu 12.04 LTS and my compile is gcc 4.9. Before your last commit on the 24 january 2017. Is broken your build  when you. The previous commit is okay.


Did you need Continuous Integration Server like jenkins to check this for you ?


Thanks


________________________________

**Comment by sgieseking** [comment]
It seems like we are not communicating well.  

The software is compiling correctly for me and others.  I have suggested that the problem is related to OS/installation specific aspects of system header files, but I can't recreate every situation for each user.  I don't have an Unbuntu 12.04 LTS installation to test.  I could create a virtual machine with this but it is not guaranteed to reproduce your problem.

Did you try adding the include of <condition_variable> to the files to see if it fixes your problem?

**Comment by mekhea** [comment]
Ok.
I will try it  to day.
If i understood that before your last commit it will work fine with linux 12.04 but nit now. Otherwise i will add the header like what you tell me.


Have a good day.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
